version: "3.8"

services:
  people-notebook:
    build: .
    container_name: people-notebook
    environment:
      - DB_PATH=/data/people.db
      - UPLOAD_DIR=/data/uploads
      # --- Телеграм уведомления о ДР (необязательно) ---
      # Создай бота @BotFather, получи токен и укажи ID чата/группы, куда слать напоминания
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
